exports.EVENT_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

exports.NOTIFICATION_TYPE = {
  APPROVAL_REQUEST: 'APPROVAL_REQUEST',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};